#!/bin/bash

if [[ $# -eq 0 ]]; then
    ./gradlew --quiet run
else
    # Join arguments in a string
    printf -v args "'%s'," "$@"
    # Remove trailing ","
    args=${args%?}

    ./gradlew --quiet -PcliArgs="[$args]" run
fi
