#!/bin/bash

if [[ $# -eq 0 ]]; then
    ./gradlew run
else
    # Join arguments in a string
    printf -v args "'%s'," "$@"
    # Remove trailing ","
    args=${args%?}

    ./gradlew run -PcliArgs="[$args]"
fi
