prefix sh: <http://www.w3.org/ns/shacl#>

SELECT ?uri ?message ?detail ?path ?value ?shape ?constraint
WHERE {
  ?vr a sh:ValidationResult .
  ?vr sh:focusNode ?uri .
  OPTIONAL {
    ?vr sh:resultMessage ?message .
  }
  OPTIONAL {
    ?vr sh:detail ?detail .
  }
  OPTIONAL {
    ?vr sh:resultPath ?path .
  }
  OPTIONAL {
    ?vr sh:value ?value.
  }
  OPTIONAL {
    ?vr sh:sourceShape ?shape .
  }
  OPTIONAL {
    ?vr sh:sourceConstraintComponent ?constraint .
  }
  OPTIONAL {
    ?vr sh:resultSeverity ?severity .
  }
}
ORDER BY ?severity ?message
